### ISSUE TITLE
Move systems out into their own directory, combine server and client code

### ISSUE THREAD

**Issue by Morgul** [Morgul/rpgkeeper#11]
Currently, our code layout is:

```
.
├── client
│   ├── components
│   ├── modals
│   ├── pages
│   ├── scss
│   ├── static
│   └── systems
├── server
│   ├── auth
│   ├── news
│   ├── routes
│   └── systems
└── vendor
```

My proposal is to turn it into this:

```
.
├── client
│   ├── components
│   ├── modals
│   ├── pages
│   ├── scss
│   └── static
├── server
│   ├── auth
│   ├── news
│   └── routes
├── systems
│   ├── generic
│   │   ├── client
│   │   └── server
│   └── eote
│       ├── client
│       └── server
└── vendor
```

This mostly just involves `Gruntfile.js`, and moving things around. (There will also be some require path changes on the client side, I think) I feel, however, that this will help keep things much cleaner, as well as keeping open the option in the future to split out the systems into their own repositories, and including them as submodules, or such.

/cc @cprieger, @Burstaholic: You guys have any thoughts on this?

**Comment by cprieger** [comment]
Is the top level client and server just for the main portion of the web page meaning the further down under systems client and server is the code specific to each one. 

My thoughts would be to move the top level client and server underneath it's own folder as well if that is the case. Then you would have 2 folders at the top level of website and systems.
