### ISSUE TITLE
Switch to TrivialModels

### ISSUE THREAD

**Issue by Morgul** [Morgul/rpgkeeper#12]
Switching to [TrivialModels](https://github.com/trivialsoftware/TrivialModels) will give us a distinct advantage going forward. First, allows developers to work on the project without installing RethinkDB. Secondly, it means that should RethinkDB, or any future system not work, all we need to do is implement a driver, and we should be able to switch with very little issue.

Currently, I'm still developing TrivialModels, but it's pretty solid at the moment. It lacks features like relations, or schema'd sub-objects/arrays, but I don't feel those are show stoppers. What we do now is pretty trivial. (Heh.)

**Comment by cprieger** [comment]
Beginning work on this now.

**Comment by Morgul** [comment]
closed by 1bedce1443cfe1963e2dc320c99f52db6d437068.
