### ISSUE TITLE
Add a loading bar when the character first loads

### ISSUE THREAD

**Issue by Morgul** [Morgul/rpgkeeper#6]
It's good to give the user some feedback that we're loading.

**Comment by cprieger** [comment]
I think what you may want to do is just add a generic progress service for both this and #7 . That way you can just invoke it via doLoad('text for what i'm doing', progress, total) or just doLoad('text') if you want the infinite spinny bars.

**Comment by Morgul** [comment]
That could definitely make sense. However, I'm not convinced that I want, say, a global modal for loading things, as opposed to putting elements in the page.

@Burstaholic Any thoughts on loading modal vs loading elements in the page?

**Comment by Morgul** [comment]
This is done in `beta`.
